### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#1]
Some stuff that I still want to do:

- [x] add dev branch, protect master branch.
- [x] automate the testing of the master branch.
- [x] add test function to create a small unstructured model, use this model to test anything unstructured instead of the big model that is used now.
- [ ] create different levels of testing, 1. create full models, 2. test existing models.
- [x] add dependencies and version numbers to the requirements

**Comment by dbrakenhoff** [comment]
See #21 for test improvements, closing this issue.
