### ISSUE TITLE
def _set_angrot_attributes(extent, xorigin, yorigin, angrot, attrs):

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#111]
`def _set_angrot_attributes(extent, xorigin, yorigin, angrot, attrs):` in resample.py requires extent to be a list and a tuple is not supported, as a tuple is immutable. modelgrid reutrns the extent as tuple.

**Comment by rubencalje** [comment]
Issue is fixed by adding the line
`extent = list(extent)`

at the start of `_set_angrot_attributes()`

**Comment by rubencalje** [comment]
Fixed in PR #115
