### ISSUE TITLE
Rename modules and methods

### ISSUE THREAD

**Issue by rubencalje** [ArtesiaWater/nlmod#115]
Before the next master release, I think we should rename/move the following modules or methods:
- mdims -> dims
- mbase -> base
- mgrid -> grid
- mlayers -> layers
- mtime -> time
- visualize.plots -> plot
- visualize.netcdf -> dataset_cross_section
- visualize.gis -> gis

Any other modules or methods we should rename? Let's do it in one go, so we only have to check tests and notebooks once.

**Comment by rubencalje** [comment]
get_heads_dataarray -> get_heads_da (or get_heads_data_array, like gdf_to_bool_data_array)

**Comment by dbrakenhoff** [comment]
Agreed, and I'd go for `_da`since we use that abbreviation all over the place.

**Comment by rubencalje** [comment]
plot.plot_vertex_array -> plot.vertex_array (will be replaced by plot.data_array in next version)
gdf_to_bool_data_array -> gdf_to_bool_da (see previous two comments)

**Comment by rubencalje** [comment]
Merged
