### ISSUE TITLE
How do we handle warnings?

### ISSUE THREAD

**Issue by rubencalje** [ArtesiaWater/nlmod#123]
In the code of nlmod there can be warnings to the user. Right now we use two methods to do this:
```
warnings.warn('message')
# or (just generating a DeprecationWarning does not reach the user)
warnings.warn('message', DeprecationWarning)
```

versus
```
logger.warning('message')
```

I think we should choose one of two methods. Using `warnings.warn` has the advantage that the user can choose to stop execution at warnings, and warnings with the same message will only show once. Using `logger.warning` has the advantage that warnings are also saved to the log-file if a log file is used, and we can better format the warning using the new color-formatter in the jupyter notebooks.

I think these last advantages are more important, so I think we should use `logger.warning` (also for DeprecationWarnings if it is up to me). Other opinions?

**Comment by OnnoEbbens** [comment]
I agree with using `logger.warning('message')`

**Comment by OnnoEbbens** [comment]
Everyone agrees :)
