### ISSUE TITLE
icvert variable converted to float when saving to NetCDF

### ISSUE THREAD

**Issue by tomvansteijn** [ArtesiaWater/nlmod#128]
The icvert variable in the nlmod model dataset is converted to float when saving to NetCDF. The variable has the attribute "_FillValue" set to -1. This attribute is lost when saving to NetCDF. The changes can cause problems when writing the DISV package. 

Is this a NetCDF issue? Or is it caused by missing values in the icvert variable for certain coordinate combinations?

**Comment by OnnoEbbens** [comment]
It has to do with how NetCDF stores missing values in an integer array. For more information see this issue: https://github.com/ArtesiaWater/nlmod/issues/91

Did you encounter problems when writing the DISV?

**Comment by rubencalje** [comment]
So the saved NetCDF-file does contain integer values for the variable `icvert`, but when you read the NetCDF again using xarray, the integer values are converted to floats, and the values equal to `_FillValue `are set to `NaN`.  To make sure this does not happen, read the NetCDF-file with the parameter `mask_and_scale` set to `False`. Like:


`ds = xr.open_dataset(fname, mask_and_scale=False)`

**Comment by tomvansteijn** [comment]
Thanks for the clarification @rubencalje. I meant to provide a working example but I haven't got to it yet. I trust this will solve the issue I had. Indeed the `_FillValue` was set to NaN, and NaN's were written to the DISV package files, with a Modflow error as a result. Good to include this  solution (about the mask_and_scale flag) in the docs if you haven't already.

**Comment by OnnoEbbens** [comment]
Fixed by https://github.com/ArtesiaWater/nlmod/pull/238
