### ISSUE TITLE
Read KNMI get Recharge

### ISSUE THREAD

**Issue by KeesdeVriesW** [ArtesiaWater/nlmod#132]
I get an error when running 
knmi_ds = nlmod.read.knmi.get_recharge(
    ds, cachedir=cachedir, cachename="recharge.nc". The error occurs in hydropandas:
TypeError: get_knmi_obslist() got an unexpected keyword argument 'starts'.
This occurs in the example /nlmod/09_schoonhoven.ipynb

**Comment by OnnoEbbens** [comment]
I think this error occurs when you use an older version of hydropandas. Can you upgrade hydropandas to the latest version 0.6.1 and see if that works? You can upgrade using:
`pip install --upgrade hydropandas`

**Comment by KeesdeVriesW** [comment]
That solved the issue. Thanks
