### ISSUE TITLE
top and base in model dataset

### ISSUE THREAD

**Issue by tomvansteijn** [ArtesiaWater/nlmod#133]
The model datasets contain the top and botm variables which describe the modellayer geometry and the kh and kv variables for the horizontal and vertical conductivities. I find it would be easier to query the dataset if it would contain top and base of each modellayer instead of 1 top value and the base (botm) for each layer. Top and botm as required by Modflow 6 discretization packages could also be computed when writing the package file. However this is probably a design choice.

**Comment by rubencalje** [comment]
Sometimes it indeed is useful to have a top and bottom of each layer. However, we decided to follow the MODFLOW-schematisation, of defining only the model top (2d) and the botm of each layer (3d). In this way, the layer model stays consistent, and we do not introduce gaps in our layer model. To avoid these gaps, we would have to make sure the botm of each layer remains equal to the top of the layer beneath.

We do make sure the botm of each layer is defined everywhere, also at locations where a layer is not present, so you can always take the botm of the previous (upper) layer to get the layer top. You can also use the method `nlmod.layers.calculate_thickness(ds)` to calculate the thickness of all layers, and add this to botm, to get a 3d top.

Maybe we should make a method of this procedure, that transforms the top to a 3d-array (like the regis-data), which you can use for visualisation or other purposes.
