### ISSUE TITLE
calculate transmissivity (kD) and resistance (c)

### ISSUE THREAD

**Issue by tomvansteijn** [ArtesiaWater/nlmod#134]
The package already contains a useful function for computing layer thicknesses. Of course it would be nice to have an additional function for calculating transmissivity and resistance as well.

**Comment by OnnoEbbens** [comment]
The formula @rubencalje describes calculates the resistance within a modellayer. I added the function `calculate_resistance` to calculate the resistance between model layers.

This function can be called using:
`nlmod.dims.calculate_resistance(ds, kv='kv', thickness='thickness')`

**Comment by OnnoEbbens** [comment]
Added both:
- resistance: `nlmod.dims.calculate_resistance(ds)`
- transmissivity: `nlmod.dims.calculate_transmissivity(ds)`
