### ISSUE TITLE
netcdf conventions for grids

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#14]
https://ugrid-conventions.github.io/ugrid-conventions/

inspired by imod-python

**Comment by bdestombe** [comment]
And the following: `https://github.com/Deltares/xugrid`

What would be the benefits of using this over what we currently have and would rely more on the flopy plot commands?

**Comment by dbrakenhoff** [comment]
I believe this interacts nicely with e.g. QGIS, so you can import your results as netcdf and they will be rendered nicely. Also it allows you to easily use imod-python tools. 

Regardless of whether we want to adopt this definition, it would be good to have a conversion between our grid definition and the ugrid one.

**Comment by bdestombe** [comment]
Okay, yes that makes sense

**Comment by bdestombe** [comment]
The recent commits of @rubencalje are super helpful, thank you. I had a question though. Wouldn't it be possible to make the required changes, to comply with being a plottable netCDF, when the disv package is contructed? E.g. in `nlmod.mfpackages.disv_from_model_ds`?

**Comment by rubencalje** [comment]
> The recent commits of @rubencalje are super helpful, thank you. I had a question though. Wouldn't it be possible to make the required changes, to comply with being a plottable netCDF, when the disv package is contructed? E.g. in `nlmod.mfpackages.disv_from_model_ds`?

Probably not. For a UGRID-netCDF file each layer of each variable has to be in a separate variable (for now), which is not very convenient in the rest of nlmod. Also, cell-vertices need to be specified in counterclockwise-direction (while flopy needs them in clockwise direction as the variable cell2d in disv), boolean variables have to be transformed to integer values and time-variables need to be transformed to float-values. To summarize, I think it is better to keep the UGRID-NetCDF-file it as an export option, like it is now.

**Comment by bdestombe** [comment]
Perfect Ruben! Thanks for the explanation. So we can close this issue?
