### ISSUE TITLE
modpath executable not up to date

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#143]
The modpath executable that is installed when running `nlmod.util.download_mfbinaries()` has an issue, see https://github.com/MODFLOW-USGS/modpath-v7/issues/27. This causes some errors in the notebooks that use modpath.

It would be nice to update `nlmod.util.download_mfbinaries()` to get newest executable.

**Comment by rubencalje** [comment]
This is implemented in PR #177
