### ISSUE TITLE
Add separate args for elevation and conductance for GHB and DRN

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#152]
Currently, when building a GHB package or DRN from a model dataset a string is passed that points to data arrays with the following logic:

```python
da_name = "my_ghb"

elev = ds[f"{da_name}_peil"]
cond = ds[f"{da_name}_cond"]
```

Besides "_peil" and "_cond" being hard-coded (ugly!) this is a bit vague in my opinion. My proposal is to add `elev` and `cond` as arguments or keyword arguments to the `ghb()` and `drn()` functions. If we opt for default values my proposal would be to use 
`"ghb_elev"` and `"ghb_cond"`, following the `"<pkg>_<flopy-variable-name>"` naming scheme.

**Comment by rubencalje** [comment]
> Besides "_peil" and "_cond" being hard-coded (ugly!) this is a bit vague in my opinion. My proposal is to add `elev` and `cond` as arguments or keyword arguments to the `ghb()` and `drn()` functions. If we opt for default values my proposal would be to use `"ghb_elev"` and `"ghb_cond"`, following the `"<pkg>_<flopy-variable-name>"` naming scheme.

I agree, and would opt for the proposed default values.
