### ISSUE TITLE
Dictionary join operator not supported in Python 3.8

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#167]
https://github.com/ArtesiaWater/nlmod/blob/feb6b466dee78e82b1d68b0321ee0666c8c86fb1/nlmod/read/meteobase.py#L193

This "|" operator is not supported in Python 3.8.

**Comment by rubencalje** [comment]
Good remark. Let's update this line by `meta.update(ascii_meta)` then?
