### ISSUE TITLE
Gridding surface water data

### ISSUE THREAD

**Issue by RdWitte** [ArtesiaWater/nlmod#168]
Today i got the following TypeError:
![image](https://user-images.githubusercontent.com/127938163/234593045-02a72e25-55df-4f1e-89c9-a228e0987755.png)

This function was working properly before last monday. I accidently updated some dependencies in my working environment along with the installation of a new package...
I assume the error has something to do with the wrong versions of shapely or Rtree. But i cannot quite pin the exact issue... I have tried multiple versions of shapely and am currently using: shapely==2.0.0 and Rtree = 0.9.7.

Are these the correct versions of these packages for nlmod? And has anyone encountered this error before?

**Comment by dbrakenhoff** [comment]
Hi @RdWitte,

I haven't seen this issue before. But it looks to me like you're on an older version of flopy, which is what might be causing the issue. What version of flopy are you using? I'd try updating flopy to version 3.3.6 first. 

Let me know if that works!

**Comment by RdWitte** [comment]
Hi Davíd,

Thanks for your response.
I reinstalled flopy and all dependencies in a new environment. Now it's working. I am still not sure what caused it.

The new environment uses the following versions:
shapely 1.8.5.post1
flopy 3.3.5
Rtree 0.9.7

**Comment by dbrakenhoff** [comment]
Hi @RdWitte,

Good to hear that its working! 
FYI, we do recommend using flopy=3.3.6 and shapely>=2.0, so you could update those packages at some point.

Cheers,

Davíd
