### ISSUE TITLE
NoData value in neerslagdata van Meteobase

### ISSUE THREAD

**Issue by JRalling** [ArtesiaWater/nlmod#171]
De code voor het inlezen van data van Meteobase is erop gemaakt dat er een NoData value aanwezig moet zijn bij de neerslag data. Dit is echter niet elke keer het geval. Zie het verschil in de bijlages.
![No_Data niet aanwezig zelf opgevraagde data ](https://user-images.githubusercontent.com/132345250/235626988-a23e125e-6fdb-49a2-942e-48e70c25be38.png)
![No_Data value test bestand](https://user-images.githubusercontent.com/132345250/235627035-29beb602-f38f-4764-8ff4-62e9fb335737.png)

**Comment by martinvonk** [comment]
Fixed by commit [77970e8](https://github.com/ArtesiaWater/nlmod/commit/77970e8becc09434b928ce9b1c13ee3131b824ee). I checked it locally so should be fine when some header entries are not listed in the ascii file.
