### ISSUE TITLE
Further improve caching by checking only relevant coordinates for certain datasets?

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#181]
When I add a timestep to a model, the cached surface elevation data (AHN) gets invalidated and it downloads the data again. This could be a smarter check I feel. Modifying the time dimension should not invalidate the AHN cache, as it only concerns spatial data and does not have a time component (in our implementation anyway). 

So, would it be possible to define the relevant coordinates to check whether certain cached datasets should be invalidated? For example,

Only spatial coordinates:
- surface elevation (AHN)
- layer models (REGIS, GeoTOP)
- ...

Spatial + time:
- surface water features?
- ...

**Comment by OnnoEbbens** [comment]
I agree that it feels like there could be a smarter check. At the moment the relevant data arrays are stored in a dataset and saved to a netcdf file together with a pickle.

I think there are two ways to do this:
1. In the cache function, before we write the dataset to a netcdf file, we can strip the coordinates from the dataset that are not used in the data variables. 
2. In the functions that create the dataset such as `get_ahn`, `get_regis` we can strip all the coordinates from the returned dataset that are not used in the data variables. This is a bit more explicit.

In both cases the cache function should be modified in such a way that we only check if the coordinates in the cached dataset are the same as in the given dataset. I see no problems as long as there are no functions in which coordinates are used to create a data array but not used for the dimensions of that data array.
