### ISSUE TITLE
Make default layer names in `get_ds` zero-based.

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#186]
When you create a model dataset with 3 layers using `nlmod.get_ds` the layers are named 1, 2, 3 by default. I propose to use the Python zero-based approach and name them 0, 1, 2.

I encountered this when trying to add DataArrays to a dataset using the steps below. It took me ages to find out what was happening.
1. I create a model dataset with 3 layers using `get_ds`. The layers are numbered 1, 2, 3
2. I create and run a model using the dataset
3. I use `nlmod.gwf.get_budget_da` to get the budget data array using the `gwf` object. This returns a DataArray with the layers numbered 0, 1, 2 because it does not know the layer numbering in the dataset.
4. I add the DataArray from step 3 to the dataset of step 1. The first layer is removed from the DataArray and a layer with only nan's is appended at the end.

**Comment by rubencalje** [comment]
The naming 1, 2, 3 was chosen so that titles in figures are one-based ('layer 1' for the first layer). But your example shows this can cause strange errors. Therefore making layer zero-based is probably better.
