### ISSUE TITLE
update readme installation section

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#190]
Since the difficult packages aren't so difficult to install on windows anymore, perhaps we can update the readme to reflect that?

**Comment by rubencalje** [comment]
Good idea. So shall we just remove the following section from [README.md](https://github.com/ArtesiaWater/nlmod/blob/main/README.md):
"When using pip the dependencies are automatically installed. Some dependencies are notoriously hard to install on certain platforms. Please see the [dependencies](https://github.com/ArtesiaWater/hydropandas#dependencies) section of the hydropandas package for more information on how to install these packages manually."

And remove the following from [getting_started.rst](https://github.com/ArtesiaWater/nlmod/blob/main/docs/getting_started.rst):
"If you run into any trouble with any of these packages during installation, refer to [this page](https://github.com/ArtesiaWater/hydropandas#dependencies) for potential solutions."
