### ISSUE TITLE
Define model active domain and document feature

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#203]
Currently, the optional data-array "active" is used in IDOMAIN calculations to inactivate sections of a dataset. 

We should clearly document this feature, and perhaps consider renaming it to "active_domain" or "active_model_domain" so it is clearer what this data variable pertains to.

**Comment by rubencalje** [comment]
It will be "active_domain".

**Comment by rubencalje** [comment]
See PR #250

**Comment by rubencalje** [comment]
Add documentation explaiing what the variable "active_domain" in ds does, in the method `nlmod.layers.get_idomain`. See PR #250.
