### ISSUE TITLE
nlmod adding rch and evt packages

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#210]
I'm running into issues adding the EVT package for a steady state model.
- evaporation data array has dimensions (time, icell2d)
- obtaining the cellids from the mask based on the evaporation data returns 2 arrays (time, and icell2d)
- getting the layers based on the first active model layer errors because it thinks there are 2 cellids (row/col) but one is actually time
- if you drop the time dimension from the mask, then it still errors because the "evaporation" data array still has dimension time

Additionally, I saw that the EVT package has some special code for steady-state models, while the recharge model does not. It seems logical to me to make these two packages behave similar.

**Comment by OnnoEbbens** [comment]
fixed in #239
