### ISSUE TITLE
Calling `extrapolate_ds()` also modifies `icvert`, causing NaN cells to be moved to location of nearest notNaN cell

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#212]
This one was confusing, but finally figured it out:
- extrapolate_ds calculates a mask where all bottoms are NaN (so where there is no layer information whatsoever)
- this mask is query each the nearest cell with data for each NaN cell.
- then all data variables are looped through and all data variables with dimensions ("icell2d") are then updated, even if there were no NaNs in that data variable to begin with.

This last step causes "icvert" to be modified by replacing the vertices of the NaN cells with those of the nearest cell. 

I used a fix to not update data if there are no NaNs in the masked data. But we could als limit the data variables you want to apply this extrapolation to, so that is something we should think about.

**Comment by OnnoEbbens** [comment]
fixed in Zeeland branch
