### ISSUE TITLE
NaN in drain package

### ISSUE THREAD

**Issue by tomvansteijn** [ArtesiaWater/nlmod#213]
When calling the function nlmod.gwf.drn NaN's are printed in the drain package file. This results in a Fortran error when trying to run the model. Within the function, a mask is created based on the conductance being not equal to zero:
```
mask = mask_arr != 0
```
However this is also true for NaN. Perhaps the expression should be adjusted?

 To be pedantic, the term 'mask' is used in the opposite sense (all other values are masked).

**Comment by tomvansteijn** [comment]
Perhaps the expression should be changed to:

```
mask = mask_arr > 0
```
This excludes NaN and ofcourse conductance is always positive.

**Comment by OnnoEbbens** [comment]
Hi Tom, thanks for pointing this out. I agree with your solution. Would you like to make a Pull Request for this? If not I am happy to make one as well.
