### ISSUE TITLE
dataarray arguments for DRN, RIV package

### ISSUE THREAD

**Issue by tomvansteijn** [ArtesiaWater/nlmod#214]
The `gwf.drn` function allow one to enter a string or a xr.DataArray for the arguments `elev` and `cond`, according to the docs. However it seems that the coordinates are not respected when using DataArray's. The function `da_to_reclist` does handle a list of floats, it seems, but does not use the coordinates in the DataArray to index conform the model dataset. Thus rivers or drains may appear upside down or mirrored in the package data and in the model results.

The same may hold for the RIV or GHB packages.

**Comment by OnnoEbbens** [comment]
Yes I see the `da_to_reclist` does not take into account the coordinates of a DataArray. I assume this error occurs when you have ascending y-coordinates in the DataArray. Is that correct? In the previous versions we had some checks for this but they may be removed. I think the best way to handle this is to add some checks for this and maybe correct it. For now a quick fix would be to make sure the y-coordinates in your DataArray are in descending order.

**Comment by tomvansteijn** [comment]
Yes indeed I had y-coordinates in ascending order. It is also possible to reindex the dataarray using the coordinates of the model dataset. In this way any mismatch between the model coordinates and the seperately provided dataarrays will become apparent.
