### ISSUE TITLE
Add units to DataArray

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#23]
It would be nice if the DataArrays that are part of model_ds would have the attribute `units`. The units are then automagically used in the labels when plotting the DataArray.

**Comment by OnnoEbbens** [comment]
Fixed this for most DataArrays. Will look further into these cases:
1. The units for the top array are not preserved when modified. 
2. The units of the NorthSea DataArray which should be unitless are set to 'mNAP'
