### ISSUE TITLE
KNMI data platform tests fail

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#272]
Two of the tests for the KNMI data platform fail (https://github.com/ArtesiaWater/nlmod/actions/runs/6559011962). I think it has something to do with data availability but I don't know exactly what went wrong. @martinvonk do you have time to look into this? And maybe while you're at it update the docstrings to include parameters and returns 😇?

**Comment by ArtesiaWater** [comment]
It seemed to be a one time thing, the test pass now
