### ISSUE TITLE
TypeError in example notebook 04_modifying_layermodels

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#31]
When running the `nlmod.mdims.mlayers.combine_layers_ds` function in the example notebook 04_modifying_layermodels I get this error:

`TypeError: Could not convert tuple of form (dims, data[, attrs, encoding]): (9, 10, 11, 12, 13) to Variable.`

I think it has something to do with commit 17ed300 because the error is exactly in the modified line.

**Comment by dbrakenhoff** [comment]
You turned thickness into an xarray.DataArray where it used to be a numpy.array ;). Which is better, but that's caused the error.
Fixed now.

**Comment by OnnoEbbens** [comment]
Ah my bet. Thanks for the fix :)
