### ISSUE TITLE
Improve plot methods, accept all gridtypes

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#35]
It would be nice to give additional colorbar kwargs to `nlmod.visualise.plots.plot_vertex_array()`. For example to shrink the colorbar.

**Comment by dbrakenhoff** [comment]
- @OnnoEbbens  check: add colorbar kwargs to `nlmod.visualise.plots.plot_vertex_array()`

**Comment by rubencalje** [comment]
Some improvements with PR #114. Notebook still needed.

**Comment by rubencalje** [comment]
Added a notbeook with commit e454fbfb2baf8ebdbeaccde26375f2ca7b6b7d8f, but more plot methods must be included.
