### ISSUE TITLE
Function to go from `model_ds` to `gwf`/`sim` and backwards

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#40]
I would like a function to create a simulation object (`sim`) from a `model_ds` object. The ds_model is easy to store and backup, while the gwf/sim is needed to use the plot functions of flopy. I can also imagine plenty of usecases for the reversed. Probably a lot of code is already part of the package. Thanks!

**Comment by OnnoEbbens** [comment]
Good idea!

**Comment by bdestombe** [comment]
These are already in "nlmod/mfpackages"
