### ISSUE TITLE
get_vertices requires rdp package

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#42]

**Comment by OnnoEbbens** [comment]
I don't know what is the optimal solution here. The rdp package makes the `get_vertices` function significantly faster but it does add a dependency.

The rdp package is only 5 functions and 180 lines of code. The last release of the rdp package was in 2016 but it is still working. It has an MIT license so we could also add the code to nlmod.

We could also optimize the `get_vertices` function and see what parts of the rdp package we actually need in this function.

What do you think is the best solution here?
1. add rdp as a depedency
2. add rdp code to nlmod
3. optimise the `get_vertices` function further and only use the parts of rdp that are actually necessary
4. ....

**Comment by rubencalje** [comment]
1 vote for solution 3

**Comment by bdestombe** [comment]
Second vote for option 3

**Comment by rubencalje** [comment]
In the end went for option 2 for simplicity, by adding one file called rdp.py. Closing the issue.
