### ISSUE TITLE
Add vertices to model_ds

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#43]
The plotting functions of nlmod require vertices. It would be nice if those were added to model_ds during grid discretisations (via `get_vertices`)

**Comment by bdestombe** [comment]
Wouldn't it be better to depend on the plotting functions of flopy? Thus via #40 provide a nice way to get back from model_ds to the flopy environment. In that case, this issue can be closed.

**Comment by dbrakenhoff** [comment]
I think a lot of flopy's plotting utilities also accept a modelgrid object? So another method would be to build the modelgrid from model_ds, and pass that onto the plotting methods.

I think `nlmod.modelgrid.mgrid.modelgrid_from_model_ds()` can do this? And this object should have methods to obtain the vertices.

**Comment by bdestombe** [comment]
@dbrakenhoff That function requires `gridprops` to be defined. Is there already a function that generates the `gridprops` from `model_ds`?

**Comment by dbrakenhoff** [comment]
Hmm, not sure if flopy has a method to convert to go from a modelgrid object to a gridprops dictionary... Shouldn't be too complicated, but it might make more sense to convert that method to use a modelgrid object instead of the much less commonly used gridprops dictionary?

**Comment by rubencalje** [comment]
> Hmm, not sure if flopy has a method to convert to go from a modelgrid object to a gridprops dictionary... Shouldn't be too complicated, but it might make more sense to convert that method to use a modelgrid object instead of the much less commonly used gridprops dictionary?

I agree, I think the modelgrid-object is a more commonly used object, that can be used to construct a disv-package or to plot model properties.

Is there a way to to save a modelgrid object to a grb-file in Flopy? It seems only MODFLOW is able to do this.

**Comment by rubencalje** [comment]
I am working on adding information from a modelgrid to a model_ds and getting a modelgrid-object from a model_ds (without needing gridprops), will add it when I am finished.

**Comment by OnnoEbbens** [comment]
fixed by #53
