### ISSUE TITLE
utils / read heads function

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#45]
I think it is one of the more recent functions in flopy. So that the code of the `get_heads_array` and `get_heads_dataarray` can be written a lot leaner:
```python
ml = sim.get_model(sim.name)

# collect heads
heads = ml.output.head().get_alldata()[:, :, 0, :]
heads[heads == ml.hdry] = np.nan
heads[heads == ml.hnoflo] = np.nan

model_ds['heads'] = xr.DataArray(
    data=heads,
    dims=('time', 'layer', 'cid'),
    attrs={'units': 'mNAP'})
```
where `ml` is the grondwater flow model, which is in other examples denoted with `gwf`. For simple cases this also works for reading the budgetfile, but for example not for the Bergen case..

The units are also stored in the flopy objects:
```
length_unit = ml.disv.length_units.get_data()
time_unit = sim.tdis.time_units.get_data()
```
It would be nice to have all all dataarrays with units. Especially with the budgetfile this is important.

**Comment by OnnoEbbens** [comment]
Yes, this looks a lot better than the current `get_heads_array` function. Some things to think about when making the changes:
- The current `get_heads_array` has an option to fill nan-values with the first non-nan-value in one of the cells below. I use this when I have model layers that are only active in part of the model extent. If I do not fill the nan-values my plot of the heads has a lot of white space. We could also leave this option out of the `get_heads_array` function and make it a separate function. In any case I think we should get rid of the current for-loop and find some xarray method to do this.
- `ml.output.head().get_alldata()` always returns a 4 dimensional array. In case we have a vertex model we only need a 3d array and in case of a structured model we need all 4 dimensions.

Do you want to implement this @bdestombe?

**Comment by dbrakenhoff** [comment]
I believe this was added by #113 and can be closed. Re-open if I'm wrong.
