### ISSUE TITLE
Expliciet maken waar data vandaan komt

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#48]
In de functie `nlmod.read.rws.get_surface_water` wordt een shapefile ingelezen met grote oppervlaktewaterlichamen. Bij het aanroepen van de functie is niet duidelijk waar deze data vandaan komt. Zorg dat bij het aanroepen van de functie expliciet wordt vermeld welke data wordt ingelezen. Geef ook de mogelijkheid om bijv. zelf een shapefile op te geven.

Dit geldt bijvoorbeeld ook voor de conversietabel voor geotop die gebruikt wordt.

**Comment by dbrakenhoff** [comment]
Figure out whether we can replace RWS surface water with BGT filtering?
