### ISSUE TITLE
Functionaliteit voor toevoegen GWT model

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#49]

**Comment by OnnoEbbens** [comment]
Op dit moment bevat nlmod nog geen functies om een transport model (gwt) toe te voegen aan een bestaand model. Dit is wel handig om bijvoorbeeld zoet/zout door te rekenen. Een voorbeeld is een functie om zoutconcentraties uit het NHI te gebruiken als randvoorwaarden voor het model.

**Comment by bdestombe** [comment]
Duidelijk, dankjewel.

**Comment by bdestombe** [comment]
Welke van de twee heeft jullie voorkeur?
 - 1 model_ds voor de gehele simulatie. Maar als je verschillende flow-/transportmodellen in dezelfde model_ds stopt kunnen de namen van de parameters clashen. Dus dan moet je afspraken maken over de naamgeving van de parameters.
 - 1 model_ds per flow-/transportmodel en dan de simulatiespecifieke parameters in iedere model_ds. In dit geval heb je weer meerdere bestanden.

Of is er een derde optie die ik over het hoofd zie?

**Comment by rubencalje** [comment]
1 model_ds voor de gehele simulatie. Dat is veel overzichtelijker denk ik.

**Comment by dbrakenhoff** [comment]
Added by #148
