### ISSUE TITLE
Functies voor aanmaken rec_list -> naamgeving verbeteren en werking verduidelijken

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#50]
Er zijn een aantal functies in de mgrid module met namen als `data_array_3d_to_rec_list` en `data_array_2d_vertex_to_rec_list` waarvan het vrij ondoorzichtig is wat ze doen en waarom ze zo'n lange naam hebben. Kijken of de structuur van deze functies verbeterd kan worden en de naamgeving logischer kan. Evt. met uitleg notebook.

Als algmene regel kan worden afgekort:
- DataArray -> da
- Dataset -> ds

**Comment by rubencalje** [comment]
I replaced all methods (`data_array_3d_to_rec_list`, `data_array_2d_vertex_to_rec_list`, `data_array_2d_vertex_to_rec_list `and `data_array_1d_vertex_to_rec_list`) by `da_to_rec_list`, one function to rule them all!

hopefully...

**Comment by dbrakenhoff** [comment]
Can be closed?
