### ISSUE TITLE
split up `nlmod.mlayers.update_model_ds_from_ml_layer_ds`

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#54]
The function `nlmod.mlayers.update_model_ds_from_ml_layer_ds` has a lot of steps that are quite unclear. Especially the `add_northsea` part should be a separate function.

**Comment by dbrakenhoff** [comment]
Also maybe the name could be improved to something like `nlmod.mlayers.add_layer_model()`?
Or `nlmod.mlayers.set_layer_model()`? Or ... ?

**Comment by OnnoEbbens** [comment]
fixed by #61
