### ISSUE TITLE
Improve `add_geotop_to_regis_hlc`

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#6]
The function to combine regis and geotop `add_geotop_to_regis_hlc` is very rigid. Is assumes there are no layers above the Holoceen in Regis. This usually works but I think a general function in which you can choose more layers that you want to replace with geotop is better.

**Comment by dbrakenhoff** [comment]
Lower priority, compare with other methods written by Ruben.
