### ISSUE TITLE
Check if boundary condition falls in inactive idomain

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#64]
Upon configuring flopy packages (several functions within nlmod/mfpackages) check if boundary condition is placed in inactive idomain to prevent errors such as placing drains/lakes in inactive cells.

**Comment by dbrakenhoff** [comment]
When recalculating IDOMAIN take into account inactive zones in model.

The following two variables define where a model is active:
- IDOMAIN
- first_active_layer

**Comment by dbrakenhoff** [comment]
- flopy checks this 
- nlmod ignores data in inactive zones (this should be logged)
- include check function `nlmod.check_idomain(var)` --> return list of inactive cellids ?
