### ISSUE TITLE
Use dask tokenize to compare xarrays in cache comparison

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#66]
https://github.com/ArtesiaWater/nlmod/blob/ce8479333b580652150e32f006fbb5823f7944ea/nlmod/cache.py#L266

I thought Dask already was a dependency of xarray and thus of the project. We could use the following:

dask.base.tokenize(model_ds)

**Comment by dbrakenhoff** [comment]
I think dask is an optional dependency of xarray. 

But what does this method allow you to do? Quick comparisons of stored/cached xarrays?

**Comment by bdestombe** [comment]
I am not completely familiar with the inner workings of the caching function, but I thought function arguments were stored in the pickle file along side the netCDF file. Doesn't the pickle file also need a hash/checksum of the netCDF file to ensure that the netCDF belongs to the pickle file. But there are probably hundreds of ways of doing this and if Dask is optional than there is probably a better way.

I foresee some issues here with working from a oneDrive/google drive, that the large netCDF is refreshed much later and is not in sync with the pickle.

**Comment by OnnoEbbens** [comment]
> I am not completely familiar with the inner workings of the caching function
Now the netCDF and the pickle file have the same file name. So a cached netcdf file 'example.nc' will have a cached pickle file 'example.pklz'.

`I foresee some issues here with working from a oneDrive/google drive, that the large netCDF is refreshed much later and is not in sync with the pickle.`
Yes, I can see this could be a problem. I think a solution could be to hash the name of the netCDF file together with the timestamp of when the netcdf file was created and use that as the name of the .pklz file. Do you think that will work?
