### ISSUE TITLE
model_ds.time uses start time of period while results are at end time

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#69]
The time coordinates of model_ds refer to the start times of each stress period, while we often much more interested in the outcomes at the end of each stress period. The times should be in sync with the ones configured in the OC package.

**Comment by rubencalje** [comment]
I think the times are already at the end of the stress period, just like you would like...

**Comment by rubencalje** [comment]
The steady state stress period is added before the supplied start-time, which may have confused you.

**Comment by bdestombe** [comment]
You were right! Thank you so much.
