### ISSUE TITLE
rioxarray as dependency

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#70]
Im not entirely shure if this is an issue, but anyways. At the moment there are two lists of requirements. One is in setup.py and the other in requirements.txt. These two lists differ and i am not completely sure if that should be the case. rioxarray for example is not present in setup.py but is listed in requirements.txt. Can't we import the requirements in setup.py from requirements.txt, so we only have to maintain a single list?

**Comment by dbrakenhoff** [comment]
I think what sometimes happens is we introduce optional dependencies for certain methods/functions. Setup.py includes everything that is necessary to be able to import the package, whereas requirements can include some optional stuff for specific methods that is then included in the requirements file for e.g. testing. These optional imports are generally contained within the functions/wrapped in try/excepts or put in files that are not imported directly. 

Having said that, rioxarray is a top level import so i think should be listed in setup.py as well.

**Comment by OnnoEbbens** [comment]
I think @martinvonk fixed something for optional dependencies in pastas and will do this for hydropandas. So maybe he can implement this for nlmod as well?

**Comment by rubencalje** [comment]
In requirements.txt are only the requirements needed for the tests. Therefore we can delete all the requirements that are allready in setup.py. This is what I have done in Pull Request #81
