### ISSUE TITLE
split `sim_tdis_gwf_ims_from_model_ds` somewhat

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#72]
I think there's a bit much going on in this method and we should split it somehow. You can't customize the solver settings here very easily, and it does not rely at all on the model_ds.

Creating each package separately is an option? Or sim + tdis, and then separating the groundwaterflow model and solver to different methods? Anyway, something to discuss. 

Also related is whether we want each and every setting (i.e. solver settings) to be stored as part of the model_ds object?

**Comment by OnnoEbbens** [comment]
I agree and just discussed this with Ruben. We think we should have the method you mentioned separated into four methods, one per package. And create another general method to create many packages (sim, tdis, gwf, ims, dis/disv, npf, oc, ic and maybe even recharge, drn) from a dataset. The last method can be used if you want to create a default model where you don't want to make decisions.
