### ISSUE TITLE
Add example building a layer_model or model_ds from scratch

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#73]
It would be useful to have examples that show how to build up a layer_model or model_ds (if that is relevant) dataset from scratch.

- What are the requisite data variables, coordinates and dimensions for the datasets? 
- Should you start from a layer_model or can you create a model_ds directly?
- Structured and unstructured examples
- ...

**Comment by rubencalje** [comment]
This is related with issue #74, where I propose to make a method called `create_default_ds`. What do you think?

**Comment by dbrakenhoff** [comment]
Closed by #110
