### ISSUE TITLE
Refine function is not a full replacement of create_vertex_grid

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#74]
create_vertex_grid just got replace with the refine function. But the refine function already expects a model_ds with x and y, while create_vertex_grid could be configured with an extent and an nrow/ncol. Can't both coexist? with create_vertex_grid being a part of the refine function.

**Comment by rubencalje** [comment]
Hmm, I am to blame for this... It is a consequence of the changed approach, in which refine is called on an existing model-ds. I would like to keep the parameters extent, nrow and ncol out of the refine-method, to keep this approach clear. Maybe we can make a new method, called `create_default_ds`, which creates a model-dataset with default values for kh, kv, top, and bottom. The code would then be:

```
ds = nlmod.mgrid.create_default_ds(extent, nrow, ncol)
ds = nlmod.mgrid.refine(ds)
```

Would that be an option for you?

**Comment by dbrakenhoff** [comment]
Both workflows are potentially useful:
1. Create grid
2. Add data to ds

OR
1. Get data
2. Regrid

**Comment by OnnoEbbens** [comment]
See also, https://github.com/ArtesiaWater/NHFLO_models/issues/22
