### ISSUE TITLE
Setting package names

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#77]
I would like to see the ability to set the package names. I am running many scenarios in a for loop by overwriting packages. Those packages are only overwritten if the package name is the same as before, otherwise the package is appended.

**Comment by dbrakenhoff** [comment]
Use **kwargs, add flopy docstring to ours?

**Comment by dbrakenhoff** [comment]
Package names can be passed through kwargs. Modelers responsibility to use name if wanted.
