### ISSUE TITLE
checking the cache with `mask_and_scale=False`

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/nlmod#91]
Sometimes the cached dataset is not used although it could be used. This has something to do with the `mask_and_scale=False` argument when I read the cached dataset.

When I read the cached dataset using `xr.open_dataset(fname_cache, mask_and_scale=False)` an extra attribute (`_FillValue:  nan`) is added to the 'x' and 'y' coordinates of the dataset. When I check if the cached dataset has the same coordinates as the original dataset (using `nlmod.cache._check_ds`) it returns `False` because of this new attribute. 

There is no problem when I remove the `mask_and_scale=False` argument. However this argument was added for a reason (although I forgot what reason) in this commit: https://github.com/ArtesiaWater/nlmod/commit/cb9f395d08095c23749e64734702786ae106276f

Code using the test dataset to recreate this problem.

```
# load dataset
ds = test_001_model.test_get_ds_from_cache("small_model")

# create cached sea.nc
ds_sea = nlmod.read.rws.get_northsea(ds, da_name="northsea", 
                                      cachedir=ds.cachedir,
                                      cachename='sea')

# read cached sea.nc
cached_ds = xr.open_dataset(os.path.join(ds.cachedir, 'sea.nc'),
                            mask_and_scale=False)

# check if dataset and cached sea dataset have the same coordinates
check = nlmod.cache._check_ds(ds, cached_ds)

assert check
```
This results in
```

INFO:nlmod.cache:coordinate x has different values in cached dataset, not using cache
AssertionError
```

**Comment by rubencalje** [comment]
The reason why you added `mask_and_scale=False` is that for a vertex grid the variable `icvert` is added to the model dataset. This variable is of integer type, and describes which vertices form each model cell. Some model cells contain less vertices than other, and `icvert` needs to contains NaN-values, which is not possible in an integer array. Therefore the attribute `_FillValue` is added to icvert, and NaN-values in `icvert `are set to this `_FillValue`.

When you read the dataset with `mask_and_scale=True`, `icvert` is transformed to floats and all values equal to `_FillValue `are set to NaNs. When you then save the netcdf to a ugrid-nc file using `nlmod.visualise.gis.model_dataset_to_ugrid_nc_file` this creates a broken file, as the variable `icvert `in the  ugrid-nc file is of type float, while qgis expects it to be of type int.

A possible solution is to check in all methods that use 'icvert' (for example in `nlmod.visualise.gis.model_dataset_to_ugrid_nc_file`) if the variable  `icvert` is of type float, and if so, to transform it to type int, using a _FillValue for NaNs. We can then allways use `mask_and_scale=True `(which is the default) when reading a model dataset. Or are there other variables that use the `_FillValue `as well?

**Comment by rubencalje** [comment]
Another option would be to replace xr.testing.assert_identical with xr.testing.assert_equal. This will not check if the attributes of the coordinates (like `_FillValue`) are equal. I prefer this solution. Or are there occasions when the attributes of coordinates matter? Hmm, the coordinated `time `probably has meaningful attributes...

Can't we just remove the `_FillValue` attribute before checking the cache?

**Comment by rubencalje** [comment]
I now remove the _FillValue, so the cache functions again. If this has negative side-effects, let me know.

**Comment by OnnoEbbens** [comment]
I am not 100% sure but I think this is related to https://github.com/ArtesiaWater/nlmod/issues/83

**Comment by OnnoEbbens** [comment]
So far it seems to work fine, closing this issue
